name: 'Setup protoc binary'
description: 'Download protoc compiler and add it to the PATH'
author: 'zchee'
inputs:
  version:
    description: 'Version to use.'
    default: '21.x'
  repo-token:
    description: 'GitHub repo token to use to avoid rate limiter'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'green'
